version: '2'
services:
  elemento-auth-client:
    image: ghcr.io/elemento-modular-cloud/elemento-auth-client:latest
    environment:
      - LOG_LEVEL=debug
      - NETWORK_HOST=0.0.0.0 
    volumes:
      - $PWD/elemento-uuids/:/root/.elemento/elemento-uuids/
    ports:
      - 47777:47777
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:47777"]
      interval: 1s
      timeout: 10s
      retries: 15
      start_period: 0s
    restart: unless-stopped

  elemento-matcher-client:
    image: ghcr.io/elemento-modular-cloud/elemento-matcher-client:latest
    environment:
      - LOG_LEVEL=debug
      - NETWORK_HOST=0.0.0.0 
      - STORAGE_CLIENT_HOST=elemento-storage-client
      - GUACAMOLE_HOST=https://nginx_guacamole_compose:443
    volumes:
      - $PWD/elemento-uuids/:/root/.elemento/elemento-uuids/
      - $PWD/elemento-matcher-client/vm-templates/:/opt/elemento/elemento-matcher-client/vm-templates/:rw
      - $PWD/hosts:/root/.elemento/hosts:ro
    depends_on:
      elemento-auth-client:
        condition: service_healthy
    ports:
      - 17777:17777
      - 7701:7701
      - 7771:7771
    restart: unless-stopped

  elemento-storage-client:
    image: ghcr.io/elemento-modular-cloud/elemento-storage-client:latest
    environment:
      - LOG_LEVEL=debug
      - NETWORK_HOST=0.0.0.0 
    volumes:
      - $PWD/elemento-uuids/:/root/.elemento/elemento-uuids/
      - $PWD/hosts:/root/.elemento/hosts:ro
    depends_on:
      elemento-auth-client:
        condition: service_healthy
    ports:
      - 27777:27777
      - 7775:7775
    restart: unless-stopped

  elemento-network-client:
    image: ghcr.io/elemento-modular-cloud/elemento-network-client:latest
    environment:
      - LOG_LEVEL=debug
      - NETWORK_HOST=0.0.0.0 
    volumes:
      - $PWD/elemento-uuids/:/root/.elemento/elemento-uuids/
      - $PWD/hosts:/root/.elemento/hosts:ro
    depends_on:
      elemento-auth-client:
        condition: service_healthy
    ports:
      - 37777:37777
    restart: unless-stopped