name: Build Electron App

on:
  push:
    branches: [ main, master ]  # Trigger on push to main/master
  pull_request:
    branches: [ main, master ]  # Trigger on PRs to main/master
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup submodules
        if: runner.os != 'Windows'
        run: |
          chmod +x ./setup.sh
        shell: bash

      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'electros-electron/package-lock.json'
