name: Build Electron App

on:
  push:
    branches: [ main, master ]  # Trigger on push to main/master
  pull_request:
    branches: [ main, master ]  # Trigger on PRs to main/master
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        
    steps:
      - name: Print CI token
        run: |
          echo ${{ secrets.CI_TOKEN }}
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Setup step
        if: runner.os != 'Windows'
        run: |
          export CI_TOKEN=${{ secrets.CI_TOKEN }}
          cd ./electros-electron
          chmod +x ./setup.sh
          ./setup.sh
        shell: bash

      - name: Populate Daemons step
        if: runner.os != 'Windows'
        run: |
          export CI_TOKEN=${{ secrets.CI_TOKEN }}
          chmod +x ./populate_daemons.sh
          ./populate_daemons.sh
        shell: bash

      - name: Build step
        if: runner.os != 'Windows'
        run: |
          cd ./electros-electron
          chmod +x ./autobuild.sh
          ./autobuild.sh
        shell: bash

      - name: List what you built
        if: runner.os != 'Windows'
        run: |
          cd ./electros-electron
          tree ./build
        shell: bash
